version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: web
      APP_PORT: 6060
    depends_on:
      web:
        condition: service_started
    restart: unless-stopped

  web:
    image: booklore/booklore:latest
    restart: on-failure
    environment:
      DATABASE_URL: jdbc:mariadb://db:3306/booklore
      DATABASE_USERNAME: bookloreuser
      DATABASE_PASSWORD: booklorepass
      BOOKLORE_PORT: "6060"
      SWAGGER_ENABLED: "false"
    depends_on:
      db:
        condition: service_started
    volumes:
      - ${APP_DATA_DIR}/data/app_data:/app/data
      - ${APP_DATA_DIR}/data/books:/books

  db:
    image: mariadb:12.0.2
    environment:
      MARIADB_DATABASE: booklore
      MARIADB_USER: bookloreuser
      MARIADB_PASSWORD: booklorepass
      MARIADB_ROOT_PASSWORD: rootpass
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 --silent || mariadb-admin ping -h 127.0.0.1 --silent"]
      interval: 10s
      timeout: 5s
      retries: 12
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/mysql
    restart: on-failure
